# Generated by Django 4.0 on 2022-01-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
