# Generated by Django 4.0 on 2022-01-19 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_service_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ('weekly_day', 'daily_hour'), 'verbose_name': 'Disponibilidade', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('title',), 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='availability',
            name='busy',
            field=models.BooleanField(default=False, verbose_name='Ocupado'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='daily_hour',
            field=models.IntegerField(choices=[(1, '06 as 07'), (2, '07 as 08'), (3, '08 as 09'), (4, '09 as 10'), (5, '10 as 11'), (6, '11 as 12'), (7, '12 as 13'), (8, '13 as 14'), (9, '14 as 15'), (10, '15 as 16'), (11, '16 as 17'), (12, '17 as 18'), (13, '18 as 19'), (14, '19 as 20'), (15, '20 as 21'), (16, '21 as 22')], verbose_name='Horário do dia'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='weekly_day',
            field=models.IntegerField(choices=[(1, 'Domingo'), (2, 'Segunda-Feira'), (3, 'Terça-Feira'), (4, 'Quarta-Feira'), (5, 'Quinta-Feira'), (6, 'Sexta-Feira'), (7, 'Sábado')], verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='availability',
            field=models.ForeignKey(limit_choices_to={'busy': False}, on_delete=django.db.models.deletion.PROTECT, to='app.availability', verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.CharField(blank=True, max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, upload_to='app/static/public/service_images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sold_off',
            field=models.BooleanField(default=False, verbose_name='A venda?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
